groups:
  - name: DemoAlerts
    rules:
      # - alert: InstanceDown 
      #   expr: up{job="services"} < 1 
      #   for: 1m
      #   labels: # labels and annotations are new
      #     severity: low
      #   annotations:
      #     summary: 'Alert with low severity.'

      - alert: InstanceDownCritical
        expr: up{job="services"} < 1 
        for: 1m 
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity (instance {{ $labels.instance }}).'

  - name: node-exporter-alerts
    rules:
      - alert: HostHighCpuLoad
        expr: (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100 > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: CPU load is > 90%\n  VALUE = {{ $value }}
      
      - alert: HostHighCpuLoad
        expr: (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100 > 70
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Host high CPU load (instance {{ $labels.instance }})
          description: CPU load is > 70%\n  VALUE = {{ $value }}

      