global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'webserver:80'
          - 'idonotexists:564'
  
  # - job_name: 'blackbox'
  #   # scheme: http
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #       - http://prometheus.io    # Target to probe with http.
  #       - https://prometheus.io   # Target to probe with https.
  #       - http://0.0.0.0:8080     # fake local web service.
  #       - http://www.google.ca
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
 
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['final_inhibit_rules-node-exporter-1:9100']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
